# Generated by Django 5.0.6 on 2024-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_rubric_bb_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Exchange'), (4, 'Rent')], default=2),
        ),
    ]
