# Generated by Django 5.0.6 on 2024-09-18 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_spare_bb_email_alter_bb_rubric_alter_bb_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Wrong title of product'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}')], verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
