# Generated by Django 5.0.6 on 2024-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_spare_advuser_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(related_name='spa1', related_query_name='spa', to='bboard.spare'),
        ),
    ]
