# Generated by Django 5.0.6 on 2024-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_alter_machine_spares'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(to='bboard.spare'),
        ),
    ]
